# Generated by Django 6.1.1 on 2026-09-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='manage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
